// src/products_data.rs
use crate::produto::Produto;

pub fn obter_produtos_exemplo() -> Vec<Produto> {
    vec![
        Produto::new(1, "Celular A".to_string(), "MarcaX".to_string(), "Eletrônicos".to_string(), 1200.0),
        Produto::new(2, "Celular B".to_string(), "MarcaY".to_string(), "Eletrônicos".to_string(), 1000.0),
        Produto::new(3, "Notebook A".to_string(), "MarcaX".to_string(), "Informática".to_string(), 3500.0),
        Produto::new(4, "Teclado Mecânico".to_string(), "MarcaZ".to_string(), "Informática".to_string(), 450.0),
        Produto::new(5, "Fone de Ouvido".to_string(), "MarcaY".to_string(), "Áudio".to_string(), 200.0),

        Produto::new(6, "Smartwatch X1".to_string(), "MarcaX".to_string(), "Eletrônicos".to_string(), 800.0),
        Produto::new(7, "Camiseta Casual".to_string(), "ModaLeve".to_string(), "Vestuário".to_string(), 70.0),
        Produto::new(8, "Calça Jeans Slim".to_string(), "JeansFit".to_string(), "Vestuário".to_string(), 150.0),
        Produto::new(9, "Tênis Esportivo".to_string(), "CorridaPro".to_string(), "Vestuário".to_string(), 250.0),
        Produto::new(10, "Relógio de Parede".to_string(), "CasaFácil".to_string(), "Decoração".to_string(), 90.0),
        Produto::new(11, "Luminária LED".to_string(), "Ilumina".to_string(), "Decoração".to_string(), 120.0),
        Produto::new(12, "Mouse Gamer".to_string(), "MarcaZ".to_string(), "Informática".to_string(), 180.0),
        Produto::new(13, "Monitor 24\"".to_string(), "MarcaX".to_string(), "Informática".to_string(), 1100.0),
        Produto::new(14, "HD Externo 1TB".to_string(), "Armazenatec".to_string(), "Informática".to_string(), 400.0),
        Produto::new(15, "Chaveiro Decorativo".to_string(), "Detalhes".to_string(), "Decoração".to_string(), 25.0),
        Produto::new(16, "Sofá Retrátil".to_string(), "ConfortLar".to_string(), "Decoração".to_string(), 2300.0),
        Produto::new(17, "Cadeira Gamer".to_string(), "GameSeat".to_string(), "Informática".to_string(), 950.0),
        Produto::new(18, "Jogo de Panelas".to_string(), "ChefTop".to_string(), "Alimentos".to_string(), 320.0),
        Produto::new(19, "Liquidificador Turbo".to_string(), "EletroMix".to_string(), "Eletrodomésticos".to_string(), 180.0),
        Produto::new(20, "Cafeteira Elétrica".to_string(), "CaféBom".to_string(), "Eletrodomésticos".to_string(), 250.0),
        Produto::new(21, "Smart TV 50\"".to_string(), "MarcaY".to_string(), "Eletrônicos".to_string(), 2800.0),
        Produto::new(22, "Bermuda Jeans".to_string(), "ModaLeve".to_string(), "Vestuário".to_string(), 90.0),
        Produto::new(23, "Vestido Floral".to_string(), "ChicVest".to_string(), "Vestuário".to_string(), 130.0),
        Produto::new(24, "Sandália Feminina".to_string(), "PassoFino".to_string(), "Vestuário".to_string(), 110.0),
        Produto::new(25, "Tapete Persa".to_string(), "DecoraLar".to_string(), "Decoração".to_string(), 1500.0),
        Produto::new(26, "Espelho de Parede".to_string(), "CasaFácil".to_string(), "Decoração".to_string(), 400.0),
        Produto::new(27, "Tablet 10\"".to_string(), "MarcaX".to_string(), "Eletrônicos".to_string(), 950.0),
        Produto::new(28, "Impressora Multifuncional".to_string(), "PrintNow".to_string(), "Informática".to_string(), 700.0),
        Produto::new(29, "Fritadeira sem Óleo".to_string(), "EletroMix".to_string(), "Eletrodomésticos".to_string(), 350.0),
        Produto::new(30, "Caixa de Som Bluetooth".to_string(), "MarcaY".to_string(), "Áudio".to_string(), 180.0),
        Produto::new(31, "Batedeira Planetária".to_string(), "CozinhaTop".to_string(), "Eletrodomésticos".to_string(), 300.0),
        Produto::new(32, "Fogão 4 Bocas".to_string(), "CozinhaTop".to_string(), "Eletrodomésticos".to_string(), 1100.0),
        Produto::new(33, "Geladeira Inverter".to_string(), "RefriaBem".to_string(), "Eletrodomésticos".to_string(), 3200.0),
        Produto::new(34, "Camiseta Estampada".to_string(), "UrbanStyle".to_string(), "Vestuário".to_string(), 85.0),
        Produto::new(35, "Shorts de Praia".to_string(), "ModaVerão".to_string(), "Vestuário".to_string(), 75.0),
        Produto::new(36, "Blusa de Frio".to_string(), "InvernoQuente".to_string(), "Vestuário".to_string(), 160.0),
        Produto::new(37, "Cachecol de Lã".to_string(), "InvernoQuente".to_string(), "Vestuário".to_string(), 60.0),
        Produto::new(38, "Almofada Decorativa".to_string(), "CasaFácil".to_string(), "Decoração".to_string(), 50.0),
        Produto::new(39, "Quadro Abstrato".to_string(), "ArteFina".to_string(), "Decoração".to_string(), 230.0),
        Produto::new(40, "Cama Box Queen".to_string(), "ConfortLar".to_string(), "Decoração".to_string(), 2100.0),
        Produto::new(41, "Mesa de Jantar".to_string(), "DecoraLar".to_string(), "Decoração".to_string(), 1900.0),
        Produto::new(42, "Suco Natural 1L".to_string(), "NatureSuco".to_string(), "Alimentos".to_string(), 10.0),
        Produto::new(43, "Biscoito Integral".to_string(), "SaúdeSnack".to_string(), "Alimentos".to_string(), 8.0),
        Produto::new(44, "Chocolate Amargo".to_string(), "DoceCacau".to_string(), "Alimentos".to_string(), 12.0),
        Produto::new(45, "Cereal Matinal".to_string(), "DespertarFit".to_string(), "Alimentos".to_string(), 15.0),
        Produto::new(46, "Notebook Gamer".to_string(), "MarcaZ".to_string(), "Informática".to_string(), 7500.0),
        Produto::new(47, "Fonte 600W".to_string(), "PCPower".to_string(), "Informática".to_string(), 350.0),
        Produto::new(48, "Memória RAM 16GB".to_string(), "Memorix".to_string(), "Informática".to_string(), 400.0),
        Produto::new(49, "Processador i7".to_string(), "Intel".to_string(), "Informática".to_string(), 1500.0),
        Produto::new(50, "Placa de Vídeo RTX".to_string(), "Nvidia".to_string(), "Informática".to_string(), 2800.0),
        Produto::new(51, "Headset Gamer".to_string(), "SoundPro".to_string(), "Áudio".to_string(), 350.0),
        Produto::new(52, "Webcam Full HD".to_string(), "MarcaZ".to_string(), "Informática".to_string(), 280.0),
        Produto::new(53, "Camiseta Polo".to_string(), "ClássicoWear".to_string(), "Vestuário".to_string(), 95.0),
        Produto::new(54, "Jaqueta Jeans".to_string(), "EstiloUrbano".to_string(), "Vestuário".to_string(), 220.0),
        Produto::new(55, "Boné Estampado".to_string(), "CabeçaFria".to_string(), "Vestuário".to_string(), 45.0),
        Produto::new(56, "Tênis Casual".to_string(), "MarcaY".to_string(), "Vestuário".to_string(), 200.0),
        Produto::new(57, "Espremedor de Frutas".to_string(), "CozinhaTop".to_string(), "Eletrodomésticos".to_string(), 140.0),
        Produto::new(58, "Panela Elétrica".to_string(), "ChefTop".to_string(), "Eletrodomésticos".to_string(), 270.0),
        Produto::new(59, "Micro-ondas 20L".to_string(), "EletroMix".to_string(), "Eletrodomésticos".to_string(), 680.0),
        Produto::new(60, "Churrasqueira Elétrica".to_string(), "GrillFast".to_string(), "Eletrodomésticos".to_string(), 430.0),
        Produto::new(61, "Refrigerante Cola 2L".to_string(), "BebidaPop".to_string(), "Alimentos".to_string(), 7.0),
        Produto::new(62, "Água Mineral 500ml".to_string(), "FonteVida".to_string(), "Alimentos".to_string(), 2.5),
        Produto::new(63, "Queijo Mussarela 500g".to_string(), "LaticíniosBom".to_string(), "Alimentos".to_string(), 22.0),
        Produto::new(64, "Presunto Fatiado 200g".to_string(), "DelíciaSul".to_string(), "Alimentos".to_string(), 10.0),
        Produto::new(65, "Feijão Carioca 1kg".to_string(), "GrãosNobres".to_string(), "Alimentos".to_string(), 6.0),
        Produto::new(66, "Arroz Branco 5kg".to_string(), "GrãosNobres".to_string(), "Alimentos".to_string(), 22.0),
        Produto::new(67, "Poltrona Reclinável".to_string(), "ConfortLar".to_string(), "Decoração".to_string(), 1800.0),
        Produto::new(68, "Cortina Blackout".to_string(), "CasaFácil".to_string(), "Decoração".to_string(), 130.0),
        Produto::new(69, "Vaso de Planta".to_string(), "NatureDecor".to_string(), "Decoração".to_string(), 70.0),
        Produto::new(70, "Jogo de Cama Queen".to_string(), "ConfortoPuro".to_string(), "Decoração".to_string(), 250.0),
        Produto::new(71, "Guarda-Roupa 6 Portas".to_string(), "MoveisTop".to_string(), "Decoração".to_string(), 2100.0),
        Produto::new(72, "Notebook Ultrafino".to_string(), "MarcaX".to_string(), "Informática".to_string(), 4200.0),
        Produto::new(73, "Teclado Sem Fio".to_string(), "MarcaZ".to_string(), "Informática".to_string(), 160.0),
        Produto::new(74, "Roteador Dual Band".to_string(), "NetRápido".to_string(), "Informática".to_string(), 240.0),
        Produto::new(75, "Pen Drive 64GB".to_string(), "Memorix".to_string(), "Informática".to_string(), 80.0),
        Produto::new(76, "Cabo HDMI 2m".to_string(), "Conecta".to_string(), "Informática".to_string(), 35.0),
        Produto::new(77, "Smartphone Z".to_string(), "MarcaZ".to_string(), "Eletrônicos".to_string(), 2200.0),
        Produto::new(78, "Leitor de Livros Digital".to_string(), "BookTech".to_string(), "Eletrônicos".to_string(), 650.0),
        Produto::new(79, "Drone Compacto".to_string(), "FlyCam".to_string(), "Eletrônicos".to_string(), 1700.0),
        Produto::new(80, "Console de Videogame".to_string(), "GameWorld".to_string(), "Eletrônicos".to_string(), 3300.0),
        Produto::new(81, "Controle Sem Fio".to_string(), "GameWorld".to_string(), "Eletrônicos".to_string(), 280.0),
        Produto::new(82, "Mochila Executiva".to_string(), "EstiloUrbano".to_string(), "Vestuário".to_string(), 160.0),
        Produto::new(83, "Carteira de Couro".to_string(), "ModaLeve".to_string(), "Vestuário".to_string(), 90.0),
        Produto::new(84, "Meia Esportiva".to_string(), "CorridaPro".to_string(), "Vestuário".to_string(), 30.0),
        Produto::new(85, "Cinto Masculino".to_string(), "ClássicoWear".to_string(), "Vestuário".to_string(), 70.0),
        Produto::new(86, "Gorro de Lã".to_string(), "InvernoQuente".to_string(), "Vestuário".to_string(), 40.0),
        Produto::new(87, "Chinelo de Borracha".to_string(), "PassoFino".to_string(), "Vestuário".to_string(), 35.0),
        Produto::new(88, "Câmera Digital".to_string(), "FotografeBem".to_string(), "Eletrônicos".to_string(), 2600.0),
        Produto::new(89, "Travesseiro Viscoelástico".to_string(), "ConfortoPuro".to_string(), "Decoração".to_string(), 120.0),
        Produto::new(90, "Açúcar Refinado 1kg".to_string(), "DocesCampos".to_string(), "Alimentos".to_string(), 4.0),
        Produto::new(91, "Sal Marinho 1kg".to_string(), "SaborNobre".to_string(), "Alimentos".to_string(), 5.0),
        Produto::new(92, "Óleo de Soja 900ml".to_string(), "CozinhaTop".to_string(), "Alimentos".to_string(), 6.5),
        Produto::new(93, "Macarrão Espaguete 500g".to_string(), "MassasItália".to_string(), "Alimentos".to_string(), 4.5),
        Produto::new(94, "Molho de Tomate 340g".to_string(), "SaborNobre".to_string(), "Alimentos".to_string(), 3.0),
        Produto::new(95, "Chá de Camomila".to_string(), "ErvasNaturais".to_string(), "Alimentos".to_string(), 6.0),
        Produto::new(96, "Cereal Granola".to_string(), "DespertarFit".to_string(), "Alimentos".to_string(), 12.0),
        Produto::new(97, "Barra de Proteína".to_string(), "NutriPower".to_string(), "Alimentos".to_string(), 8.5),
        Produto::new(98, "Suplemento Whey 900g".to_string(), "NutriPower".to_string(), "Alimentos".to_string(), 95.0),
        Produto::new(99, "Balança Digital".to_string(), "CasaFit".to_string(), "Eletrônicos".to_string(), 130.0),
        Produto::new(100, "Umidificador de Ar".to_string(), "ClimaBom".to_string(), "Eletrônicos".to_string(), 210.0),
    ]
}

